/*
 * Copyright (C) 2024 Nikolas Koesling <nikolas@koesling.info>.
 * This program is free software. You can redistribute it and/or modify it under the terms of the MIT License.
 */

// This file is automatically generated. DO NOT CHANGE!

#include "version_info.hpp"

const std::string XXXPROJECT_NAMEXXX_version_info::VERSION_STR(PROJECT_VERSION);
const std::string XXXPROJECT_NAMEXXX_version_info::NAME(PROJECT_NAME);
const std::string XXXPROJECT_NAMEXXX_version_info::COMPILER(COMPILER_INFO);
const std::string XXXPROJECT_NAMEXXX_version_info::SYSTEM(SYSTEM_INFO);
const std::string XXXPROJECT_NAMEXXX_version_info::GIT_HASH("XXXGIT_HASHXXX");
