/*
 * Copyright (C) 2022 Nikolas Koesling <nikolas@koesling.info>.
 * This program is free software. You can redistribute it and/or modify it under the terms of the GPLv3 License.
 */

#include "license.hpp"

void print_licenses(std::ostream &o, bool full) {
    // #################################################################################################################
    // #################################################################################################################
    // This App
    // #################################################################################################################
    // #################################################################################################################
    o << "This Application (" << PROJECT_NAME << ' ' << PROJECT_VERSION "): \n";
    o << "\n";
    o << "    GPLv3\n";
    if (full) {
        o << "\n";
        o << "    GNU GENERAL PUBLIC LICENSE\n";
        o << "    Version 3, 29 June 2007\n";
        o << "\n";
        o << "    Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>\n";
        o << "    Everyone is permitted to copy and distribute verbatim copies\n";
        o << "    of this license document, but changing it is not allowed.\n";
        o << "\n";
        o << "    Preamble\n";
        o << "\n";
        o << "    The GNU General Public License is a free, copyleft license for\n";
        o << "    software and other kinds of works.\n";
        o << "\n";
        o << "    The licenses for most software and other practical works are designed\n";
        o << "    to take away your freedom to share and change the works.  By contrast,\n";
        o << "    the GNU General Public License is intended to guarantee your freedom to\n";
        o << "    share and change all versions of a program--to make sure it remains free\n";
        o << "    software for all its users.  We, the Free Software Foundation, use the\n";
        o << "    GNU General Public License for most of our software; it applies also to\n";
        o << "    any other work released this way by its authors.  You can apply it to\n";
        o << "    your programs, too.\n";
        o << "\n";
        o << "    When we speak of free software, we are referring to freedom, not\n";
        o << "    price.  Our General Public Licenses are designed to make sure that you\n";
        o << "    have the freedom to distribute copies of free software (and charge for\n";
        o << "    them if you wish), that you receive source code or can get it if you\n";
        o << "    want it, that you can change the software or use pieces of it in new\n";
        o << "    free programs, and that you know you can do these things.\n";
        o << "\n";
        o << "    To protect your rights, we need to prevent others from denying you\n";
        o << "    these rights or asking you to surrender the rights.  Therefore, you have\n";
        o << "    certain responsibilities if you distribute copies of the software, or if\n";
        o << "    you modify it: responsibilities to respect the freedom of others.\n";
        o << "\n";
        o << "    For example, if you distribute copies of such a program, whether\n";
        o << "    gratis or for a fee, you must pass on to the recipients the same\n";
        o << "    freedoms that you received.  You must make sure that they, too, receive\n";
        o << "    or can get the source code.  And you must show them these terms so they\n";
        o << "    know their rights.\n";
        o << "\n";
        o << "    Developers that use the GNU GPL protect your rights with two steps:\n";
        o << "    (1) assert copyright on the software, and (2) offer you this License\n";
        o << "    giving you legal permission to copy, distribute and/or modify it.\n";
        o << "\n";
        o << "    For the developers' and authors' protection, the GPL clearly explains\n";
        o << "    that there is no warranty for this free software.  For both users' and\n";
        o << "    authors' sake, the GPL requires that modified versions be marked as\n";
        o << "    changed, so that their problems will not be attributed erroneously to\n";
        o << "    authors of previous versions.\n";
        o << "\n";
        o << "    Some devices are designed to deny users access to install or run\n";
        o << "    modified versions of the software inside them, although the manufacturer\n";
        o << "    can do so.  This is fundamentally incompatible with the aim of\n";
        o << "    protecting users' freedom to change the software.  The systematic\n";
        o << "    pattern of such abuse occurs in the area of products for individuals to\n";
        o << "    use, which is precisely where it is most unacceptable.  Therefore, we\n";
        o << "    have designed this version of the GPL to prohibit the practice for those\n";
        o << "    products.  If such problems arise substantially in other domains, we\n";
        o << "    stand ready to extend this provision to those domains in future versions\n";
        o << "    of the GPL, as needed to protect the freedom of users.\n";
        o << "\n";
        o << "    Finally, every program is threatened constantly by software patents.\n";
        o << "    States should not allow patents to restrict development and use of\n";
        o << "    software on general-purpose computers, but in those that do, we wish to\n";
        o << "    avoid the special danger that patents applied to a free program could\n";
        o << "    make it effectively proprietary.  To prevent this, the GPL assures that\n";
        o << "    patents cannot be used to render the program non-free.\n";
        o << "\n";
        o << "    The precise terms and conditions for copying, distribution and\n";
        o << "    modification follow.\n";
        o << "\n";
        o << "    TERMS AND CONDITIONS\n";
        o << "\n";
        o << "    0. Definitions.\n";
        o << "\n";
        o << "    \"This License\" refers to version 3 of the GNU General Public License.\n";
        o << "\n";
        o << "    \"Copyright\" also means copyright-like laws that apply to other kinds of\n";
        o << "    works, such as semiconductor masks.\n";
        o << "\n";
        o << "    \"The Program\" refers to any copyrightable work licensed under this\n";
        o << "    License.  Each licensee is addressed as \"you\".  \"Licensees\" and\n";
        o << "    \"recipients\" may be individuals or organizations.\n";
        o << "\n";
        o << "    To \"modify\" a work means to copy from or adapt all or part of the work\n";
        o << "    in a fashion requiring copyright permission, other than the making of an\n";
        o << "    exact copy.  The resulting work is called a \"modified version\" of the\n";
        o << "    earlier work or a work \"based on\" the earlier work.\n";
        o << "\n";
        o << "    A \"covered work\" means either the unmodified Program or a work based\n";
        o << "    on the Program.\n";
        o << "\n";
        o << "    To \"propagate\" a work means to do anything with it that, without\n";
        o << "    permission, would make you directly or secondarily liable for\n";
        o << "    infringement under applicable copyright law, except executing it on a\n";
        o << "    computer or modifying a private copy.  Propagation includes copying,\n";
        o << "    distribution (with or without modification), making available to the\n";
        o << "    public, and in some countries other activities as well.\n";
        o << "\n";
        o << "    To \"convey\" a work means any kind of propagation that enables other\n";
        o << "    parties to make or receive copies.  Mere interaction with a user through\n";
        o << "    a computer network, with no transfer of a copy, is not conveying.\n";
        o << "\n";
        o << "    An interactive user interface displays \"Appropriate Legal Notices\"\n";
        o << "    to the extent that it includes a convenient and prominently visible\n";
        o << "    feature that (1) displays an appropriate copyright notice, and (2)\n";
        o << "    tells the user that there is no warranty for the work (except to the\n";
        o << "    extent that warranties are provided), that licensees may convey the\n";
        o << "    work under this License, and how to view a copy of this License.  If\n";
        o << "    the interface presents a list of user commands or options, such as a\n";
        o << "    menu, a prominent item in the list meets this criterion.\n";
        o << "\n";
        o << "    1. Source Code.\n";
        o << "\n";
        o << "    The \"source code\" for a work means the preferred form of the work\n";
        o << "    for making modifications to it.  \"Object code\" means any non-source\n";
        o << "    form of a work.\n";
        o << "\n";
        o << "    A \"Standard Interface\" means an interface that either is an official\n";
        o << "    standard defined by a recognized standards body, or, in the case of\n";
        o << "    interfaces specified for a particular programming language, one that\n";
        o << "    is widely used among developers working in that language.\n";
        o << "\n";
        o << "    The \"System Libraries\" of an executable work include anything, other\n";
        o << "    than the work as a whole, that (a) is included in the normal form of\n";
        o << "    packaging a Major Component, but which is not part of that Major\n";
        o << "    Component, and (b) serves only to enable use of the work with that\n";
        o << "    Major Component, or to implement a Standard Interface for which an\n";
        o << "    implementation is available to the public in source code form.  A\n";
        o << "    \"Major Component\", in this context, means a major essential component\n";
        o << "    (kernel, window system, and so on) of the specific operating system\n";
        o << "    (if any) on which the executable work runs, or a compiler used to\n";
        o << "    produce the work, or an object code interpreter used to run it.\n";
        o << "\n";
        o << "    The \"Corresponding Source\" for a work in object code form means all\n";
        o << "    the source code needed to generate, install, and (for an executable\n";
        o << "    work) run the object code and to modify the work, including scripts to\n";
        o << "    control those activities.  However, it does not include the work's\n";
        o << "    System Libraries, or general-purpose tools or generally available free\n";
        o << "    programs which are used unmodified in performing those activities but\n";
        o << "    which are not part of the work.  For example, Corresponding Source\n";
        o << "    includes interface definition files associated with source files for\n";
        o << "    the work, and the source code for shared libraries and dynamically\n";
        o << "    linked subprograms that the work is specifically designed to require,\n";
        o << "    such as by intimate data communication or control flow between those\n";
        o << "    subprograms and other parts of the work.\n";
        o << "\n";
        o << "    The Corresponding Source need not include anything that users\n";
        o << "    can regenerate automatically from other parts of the Corresponding\n";
        o << "    Source.\n";
        o << "\n";
        o << "    The Corresponding Source for a work in source code form is that\n";
        o << "    same work.\n";
        o << "\n";
        o << "    2. Basic Permissions.\n";
        o << "\n";
        o << "    All rights granted under this License are granted for the term of\n";
        o << "    copyright on the Program, and are irrevocable provided the stated\n";
        o << "    conditions are met.  This License explicitly affirms your unlimited\n";
        o << "    permission to run the unmodified Program.  The output from running a\n";
        o << "    covered work is covered by this License only if the output, given its\n";
        o << "    content, constitutes a covered work.  This License acknowledges your\n";
        o << "    rights of fair use or other equivalent, as provided by copyright law.\n";
        o << "\n";
        o << "    You may make, run and propagate covered works that you do not\n";
        o << "    convey, without conditions so long as your license otherwise remains\n";
        o << "    in force.  You may convey covered works to others for the sole purpose\n";
        o << "    of having them make modifications exclusively for you, or provide you\n";
        o << "    with facilities for running those works, provided that you comply with\n";
        o << "    the terms of this License in conveying all material for which you do\n";
        o << "    not control copyright.  Those thus making or running the covered works\n";
        o << "    for you must do so exclusively on your behalf, under your direction\n";
        o << "    and control, on terms that prohibit them from making any copies of\n";
        o << "    your copyrighted material outside their relationship with you.\n";
        o << "\n";
        o << "    Conveying under any other circumstances is permitted solely under\n";
        o << "    the conditions stated below.  Sublicensing is not allowed; section 10\n";
        o << "    makes it unnecessary.\n";
        o << "\n";
        o << "    3. Protecting Users' Legal Rights From Anti-Circumvention Law.\n";
        o << "\n";
        o << "    No covered work shall be deemed part of an effective technological\n";
        o << "    measure under any applicable law fulfilling obligations under article\n";
        o << "    11 of the WIPO copyright treaty adopted on 20 December 1996, or\n";
        o << "    similar laws prohibiting or restricting circumvention of such\n";
        o << "    measures.\n";
        o << "\n";
        o << "    When you convey a covered work, you waive any legal power to forbid\n";
        o << "    circumvention of technological measures to the extent such circumvention\n";
        o << "    is effected by exercising rights under this License with respect to\n";
        o << "    the covered work, and you disclaim any intention to limit operation or\n";
        o << "    modification of the work as a means of enforcing, against the work's\n";
        o << "    users, your or third parties' legal rights to forbid circumvention of\n";
        o << "    technological measures.\n";
        o << "\n";
        o << "    4. Conveying Verbatim Copies.\n";
        o << "\n";
        o << "    You may convey verbatim copies of the Program's source code as you\n";
        o << "    receive it, in any medium, provided that you conspicuously and\n";
        o << "    appropriately publish on each copy an appropriate copyright notice;\n";
        o << "    keep intact all notices stating that this License and any\n";
        o << "    non-permissive terms added in accord with section 7 apply to the code;\n";
        o << "    keep intact all notices of the absence of any warranty; and give all\n";
        o << "    recipients a copy of this License along with the Program.\n";
        o << "\n";
        o << "    You may charge any price or no price for each copy that you convey,\n";
        o << "    and you may offer support or warranty protection for a fee.\n";
        o << "\n";
        o << "    5. Conveying Modified Source Versions.\n";
        o << "\n";
        o << "    You may convey a work based on the Program, or the modifications to\n";
        o << "    produce it from the Program, in the form of source code under the\n";
        o << "    terms of section 4, provided that you also meet all of these conditions:\n";
        o << "\n";
        o << "    a) The work must carry prominent notices stating that you modified\n";
        o << "    it, and giving a relevant date.\n";
        o << "\n";
        o << "    b) The work must carry prominent notices stating that it is\n";
        o << "    released under this License and any conditions added under section\n";
        o << "    7.  This requirement modifies the requirement in section 4 to\n";
        o << "    \"keep intact all notices\".\n";
        o << "\n";
        o << "    c) You must license the entire work, as a whole, under this\n";
        o << "    License to anyone who comes into possession of a copy.  This\n";
        o << "    License will therefore apply, along with any applicable section 7\n";
        o << "    additional terms, to the whole of the work, and all its parts,\n";
        o << "    regardless of how they are packaged.  This License gives no\n";
        o << "    permission to license the work in any other way, but it does not\n";
        o << "    invalidate such permission if you have separately received it.\n";
        o << "\n";
        o << "    d) If the work has interactive user interfaces, each must display\n";
        o << "    Appropriate Legal Notices; however, if the Program has interactive\n";
        o << "    interfaces that do not display Appropriate Legal Notices, your\n";
        o << "    work need not make them do so.\n";
        o << "\n";
        o << "    A compilation of a covered work with other separate and independent\n";
        o << "    works, which are not by their nature extensions of the covered work,\n";
        o << "    and which are not combined with it such as to form a larger program,\n";
        o << "    in or on a volume of a storage or distribution medium, is called an\n";
        o << "    \"aggregate\" if the compilation and its resulting copyright are not\n";
        o << "    used to limit the access or legal rights of the compilation's users\n";
        o << "    beyond what the individual works permit.  Inclusion of a covered work\n";
        o << "    in an aggregate does not cause this License to apply to the other\n";
        o << "    parts of the aggregate.\n";
        o << "\n";
        o << "    6. Conveying Non-Source Forms.\n";
        o << "\n";
        o << "    You may convey a covered work in object code form under the terms\n";
        o << "    of sections 4 and 5, provided that you also convey the\n";
        o << "    machine-readable Corresponding Source under the terms of this License,\n";
        o << "    in one of these ways:\n";
        o << "\n";
        o << "    a) Convey the object code in, or embodied in, a physical product\n";
        o << "    (including a physical distribution medium), accompanied by the\n";
        o << "    Corresponding Source fixed on a durable physical medium\n";
        o << "    customarily used for software interchange.\n";
        o << "\n";
        o << "    b) Convey the object code in, or embodied in, a physical product\n";
        o << "    (including a physical distribution medium), accompanied by a\n";
        o << "    written offer, valid for at least three years and valid for as\n";
        o << "    long as you offer spare parts or customer support for that product\n";
        o << "    model, to give anyone who possesses the object code either (1) a\n";
        o << "    copy of the Corresponding Source for all the software in the\n";
        o << "    product that is covered by this License, on a durable physical\n";
        o << "    medium customarily used for software interchange, for a price no\n";
        o << "    more than your reasonable cost of physically performing this\n";
        o << "    conveying of source, or (2) access to copy the\n";
        o << "    Corresponding Source from a network server at no charge.\n";
        o << "\n";
        o << "    c) Convey individual copies of the object code with a copy of the\n";
        o << "    written offer to provide the Corresponding Source.  This\n";
        o << "    alternative is allowed only occasionally and noncommercially, and\n";
        o << "    only if you received the object code with such an offer, in accord\n";
        o << "    with subsection 6b.\n";
        o << "\n";
        o << "    d) Convey the object code by offering access from a designated\n";
        o << "    place (gratis or for a charge), and offer equivalent access to the\n";
        o << "    Corresponding Source in the same way through the same place at no\n";
        o << "    further charge.  You need not require recipients to copy the\n";
        o << "    Corresponding Source along with the object code.  If the place to\n";
        o << "    copy the object code is a network server, the Corresponding Source\n";
        o << "    may be on a different server (operated by you or a third party)\n";
        o << "    that supports equivalent copying facilities, provided you maintain\n";
        o << "    clear directions next to the object code saying where to find the\n";
        o << "    Corresponding Source.  Regardless of what server hosts the\n";
        o << "    Corresponding Source, you remain obligated to ensure that it is\n";
        o << "    available for as long as needed to satisfy these requirements.\n";
        o << "\n";
        o << "    e) Convey the object code using peer-to-peer transmission, provided\n";
        o << "    you inform other peers where the object code and Corresponding\n";
        o << "    Source of the work are being offered to the general public at no\n";
        o << "    charge under subsection 6d.\n";
        o << "\n";
        o << "    A separable portion of the object code, whose source code is excluded\n";
        o << "    from the Corresponding Source as a System Library, need not be\n";
        o << "    included in conveying the object code work.\n";
        o << "\n";
        o << "    A \"User Product\" is either (1) a \"consumer product\", which means any\n";
        o << "    tangible personal property which is normally used for personal, family,\n";
        o << "    or household purposes, or (2) anything designed or sold for incorporation\n";
        o << "    into a dwelling.  In determining whether a product is a consumer product,\n";
        o << "    doubtful cases shall be resolved in favor of coverage.  For a particular\n";
        o << "    product received by a particular user, \"normally used\" refers to a\n";
        o << "    typical or common use of that class of product, regardless of the status\n";
        o << "    of the particular user or of the way in which the particular user\n";
        o << "    actually uses, or expects or is expected to use, the product.  A product\n";
        o << "    is a consumer product regardless of whether the product has substantial\n";
        o << "    commercial, industrial or non-consumer uses, unless such uses represent\n";
        o << "    the only significant mode of use of the product.\n";
        o << "\n";
        o << "    \"Installation Information\" for a User Product means any methods,\n";
        o << "    procedures, authorization keys, or other information required to install\n";
        o << "    and execute modified versions of a covered work in that User Product from\n";
        o << "    a modified version of its Corresponding Source.  The information must\n";
        o << "    suffice to ensure that the continued functioning of the modified object\n";
        o << "    code is in no case prevented or interfered with solely because\n";
        o << "    modification has been made.\n";
        o << "\n";
        o << "    If you convey an object code work under this section in, or with, or\n";
        o << "    specifically for use in, a User Product, and the conveying occurs as\n";
        o << "    part of a transaction in which the right of possession and use of the\n";
        o << "    User Product is transferred to the recipient in perpetuity or for a\n";
        o << "    fixed term (regardless of how the transaction is characterized), the\n";
        o << "    Corresponding Source conveyed under this section must be accompanied\n";
        o << "    by the Installation Information.  But this requirement does not apply\n";
        o << "    if neither you nor any third party retains the ability to install\n";
        o << "    modified object code on the User Product (for example, the work has\n";
        o << "    been installed in ROM).\n";
        o << "\n";
        o << "    The requirement to provide Installation Information does not include a\n";
        o << "    requirement to continue to provide support service, warranty, or updates\n";
        o << "    for a work that has been modified or installed by the recipient, or for\n";
        o << "    the User Product in which it has been modified or installed.  Access to a\n";
        o << "    network may be denied when the modification itself materially and\n";
        o << "    adversely affects the operation of the network or violates the rules and\n";
        o << "    protocols for communication across the network.\n";
        o << "\n";
        o << "    Corresponding Source conveyed, and Installation Information provided,\n";
        o << "    in accord with this section must be in a format that is publicly\n";
        o << "    documented (and with an implementation available to the public in\n";
        o << "    source code form), and must require no special password or key for\n";
        o << "    unpacking, reading or copying.\n";
        o << "\n";
        o << "    7. Additional Terms.\n";
        o << "\n";
        o << "    \"Additional permissions\" are terms that supplement the terms of this\n";
        o << "    License by making exceptions from one or more of its conditions.\n";
        o << "    Additional permissions that are applicable to the entire Program shall\n";
        o << "    be treated as though they were included in this License, to the extent\n";
        o << "    that they are valid under applicable law.  If additional permissions\n";
        o << "    apply only to part of the Program, that part may be used separately\n";
        o << "    under those permissions, but the entire Program remains governed by\n";
        o << "    this License without regard to the additional permissions.\n";
        o << "\n";
        o << "    When you convey a copy of a covered work, you may at your option\n";
        o << "    remove any additional permissions from that copy, or from any part of\n";
        o << "    it.  (Additional permissions may be written to require their own\n";
        o << "    removal in certain cases when you modify the work.)  You may place\n";
        o << "    additional permissions on material, added by you to a covered work,\n";
        o << "    for which you have or can give appropriate copyright permission.\n";
        o << "\n";
        o << "    Notwithstanding any other provision of this License, for material you\n";
        o << "    add to a covered work, you may (if authorized by the copyright holders of\n";
        o << "    that material) supplement the terms of this License with terms:\n";
        o << "\n";
        o << "    a) Disclaiming warranty or limiting liability differently from the\n";
        o << "    terms of sections 15 and 16 of this License; or\n";
        o << "\n";
        o << "    b) Requiring preservation of specified reasonable legal notices or\n";
        o << "    author attributions in that material or in the Appropriate Legal\n";
        o << "    Notices displayed by works containing it; or\n";
        o << "\n";
        o << "    c) Prohibiting misrepresentation of the origin of that material, or\n";
        o << "    requiring that modified versions of such material be marked in\n";
        o << "    reasonable ways as different from the original version; or\n";
        o << "\n";
        o << "    d) Limiting the use for publicity purposes of names of licensors or\n";
        o << "    authors of the material; or\n";
        o << "\n";
        o << "    e) Declining to grant rights under trademark law for use of some\n";
        o << "    trade names, trademarks, or service marks; or\n";
        o << "\n";
        o << "    f) Requiring indemnification of licensors and authors of that\n";
        o << "    material by anyone who conveys the material (or modified versions of\n";
        o << "    it) with contractual assumptions of liability to the recipient, for\n";
        o << "    any liability that these contractual assumptions directly impose on\n";
        o << "    those licensors and authors.\n";
        o << "\n";
        o << "    All other non-permissive additional terms are considered \"further\n";
        o << "    restrictions\" within the meaning of section 10.  If the Program as you\n";
        o << "    received it, or any part of it, contains a notice stating that it is\n";
        o << "    governed by this License along with a term that is a further\n";
        o << "    restriction, you may remove that term.  If a license document contains\n";
        o << "    a further restriction but permits relicensing or conveying under this\n";
        o << "    License, you may add to a covered work material governed by the terms\n";
        o << "    of that license document, provided that the further restriction does\n";
        o << "    not survive such relicensing or conveying.\n";
        o << "\n";
        o << "    If you add terms to a covered work in accord with this section, you\n";
        o << "    must place, in the relevant source files, a statement of the\n";
        o << "    additional terms that apply to those files, or a notice indicating\n";
        o << "    where to find the applicable terms.\n";
        o << "\n";
        o << "    Additional terms, permissive or non-permissive, may be stated in the\n";
        o << "    form of a separately written license, or stated as exceptions;\n";
        o << "    the above requirements apply either way.\n";
        o << "\n";
        o << "    8. Termination.\n";
        o << "\n";
        o << "    You may not propagate or modify a covered work except as expressly\n";
        o << "    provided under this License.  Any attempt otherwise to propagate or\n";
        o << "    modify it is void, and will automatically terminate your rights under\n";
        o << "    this License (including any patent licenses granted under the third\n";
        o << "    paragraph of section 11).\n";
        o << "\n";
        o << "    However, if you cease all violation of this License, then your\n";
        o << "    license from a particular copyright holder is reinstated (a)\n";
        o << "    provisionally, unless and until the copyright holder explicitly and\n";
        o << "    finally terminates your license, and (b) permanently, if the copyright\n";
        o << "    holder fails to notify you of the violation by some reasonable means\n";
        o << "    prior to 60 days after the cessation.\n";
        o << "\n";
        o << "    Moreover, your license from a particular copyright holder is\n";
        o << "    reinstated permanently if the copyright holder notifies you of the\n";
        o << "    violation by some reasonable means, this is the first time you have\n";
        o << "    received notice of violation of this License (for any work) from that\n";
        o << "    copyright holder, and you cure the violation prior to 30 days after\n";
        o << "    your receipt of the notice.\n";
        o << "\n";
        o << "    Termination of your rights under this section does not terminate the\n";
        o << "    licenses of parties who have received copies or rights from you under\n";
        o << "    this License.  If your rights have been terminated and not permanently\n";
        o << "    reinstated, you do not qualify to receive new licenses for the same\n";
        o << "    material under section 10.\n";
        o << "\n";
        o << "    9. Acceptance Not Required for Having Copies.\n";
        o << "\n";
        o << "    You are not required to accept this License in order to receive or\n";
        o << "    run a copy of the Program.  Ancillary propagation of a covered work\n";
        o << "    occurring solely as a consequence of using peer-to-peer transmission\n";
        o << "    to receive a copy likewise does not require acceptance.  However,\n";
        o << "    nothing other than this License grants you permission to propagate or\n";
        o << "    modify any covered work.  These actions infringe copyright if you do\n";
        o << "    not accept this License.  Therefore, by modifying or propagating a\n";
        o << "    covered work, you indicate your acceptance of this License to do so.\n";
        o << "\n";
        o << "    10. Automatic Licensing of Downstream Recipients.\n";
        o << "\n";
        o << "    Each time you convey a covered work, the recipient automatically\n";
        o << "    receives a license from the original licensors, to run, modify and\n";
        o << "    propagate that work, subject to this License.  You are not responsible\n";
        o << "    for enforcing compliance by third parties with this License.\n";
        o << "\n";
        o << "    An \"entity transaction\" is a transaction transferring control of an\n";
        o << "    organization, or substantially all assets of one, or subdividing an\n";
        o << "    organization, or merging organizations.  If propagation of a covered\n";
        o << "    work results from an entity transaction, each party to that\n";
        o << "    transaction who receives a copy of the work also receives whatever\n";
        o << "    licenses to the work the party's predecessor in interest had or could\n";
        o << "    give under the previous paragraph, plus a right to possession of the\n";
        o << "    Corresponding Source of the work from the predecessor in interest, if\n";
        o << "    the predecessor has it or can get it with reasonable efforts.\n";
        o << "\n";
        o << "    You may not impose any further restrictions on the exercise of the\n";
        o << "    rights granted or affirmed under this License.  For example, you may\n";
        o << "    not impose a license fee, royalty, or other charge for exercise of\n";
        o << "    rights granted under this License, and you may not initiate litigation\n";
        o << "    (including a cross-claim or counterclaim in a lawsuit) alleging that\n";
        o << "    any patent claim is infringed by making, using, selling, offering for\n";
        o << "    sale, or importing the Program or any portion of it.\n";
        o << "\n";
        o << "    11. Patents.\n";
        o << "\n";
        o << "    A \"contributor\" is a copyright holder who authorizes use under this\n";
        o << "    License of the Program or a work on which the Program is based.  The\n";
        o << "    work thus licensed is called the contributor's \"contributor version\".\n";
        o << "\n";
        o << "    A contributor's \"essential patent claims\" are all patent claims\n";
        o << "    owned or controlled by the contributor, whether already acquired or\n";
        o << "    hereafter acquired, that would be infringed by some manner, permitted\n";
        o << "    by this License, of making, using, or selling its contributor version,\n";
        o << "    but do not include claims that would be infringed only as a\n";
        o << "    consequence of further modification of the contributor version.  For\n";
        o << "    purposes of this definition, \"control\" includes the right to grant\n";
        o << "    patent sublicenses in a manner consistent with the requirements of\n";
        o << "    this License.\n";
        o << "\n";
        o << "    Each contributor grants you a non-exclusive, worldwide, royalty-free\n";
        o << "    patent license under the contributor's essential patent claims, to\n";
        o << "    make, use, sell, offer for sale, import and otherwise run, modify and\n";
        o << "    propagate the contents of its contributor version.\n";
        o << "\n";
        o << "    In the following three paragraphs, a \"patent license\" is any express\n";
        o << "    agreement or commitment, however denominated, not to enforce a patent\n";
        o << "    (such as an express permission to practice a patent or covenant not to\n";
        o << "    sue for patent infringement).  To \"grant\" such a patent license to a\n";
        o << "    party means to make such an agreement or commitment not to enforce a\n";
        o << "    patent against the party.\n";
        o << "\n";
        o << "    If you convey a covered work, knowingly relying on a patent license,\n";
        o << "    and the Corresponding Source of the work is not available for anyone\n";
        o << "    to copy, free of charge and under the terms of this License, through a\n";
        o << "    publicly available network server or other readily accessible means,\n";
        o << "    then you must either (1) cause the Corresponding Source to be so\n";
        o << "    available, or (2) arrange to deprive yourself of the benefit of the\n";
        o << "    patent license for this particular work, or (3) arrange, in a manner\n";
        o << "    consistent with the requirements of this License, to extend the patent\n";
        o << "    license to downstream recipients.  \"Knowingly relying\" means you have\n";
        o << "    actual knowledge that, but for the patent license, your conveying the\n";
        o << "    covered work in a country, or your recipient's use of the covered work\n";
        o << "    in a country, would infringe one or more identifiable patents in that\n";
        o << "    country that you have reason to believe are valid.\n";
        o << "\n";
        o << "    If, pursuant to or in connection with a single transaction or\n";
        o << "    arrangement, you convey, or propagate by procuring conveyance of, a\n";
        o << "    covered work, and grant a patent license to some of the parties\n";
        o << "    receiving the covered work authorizing them to use, propagate, modify\n";
        o << "    or convey a specific copy of the covered work, then the patent license\n";
        o << "    you grant is automatically extended to all recipients of the covered\n";
        o << "    work and works based on it.\n";
        o << "\n";
        o << "    A patent license is \"discriminatory\" if it does not include within\n";
        o << "    the scope of its coverage, prohibits the exercise of, or is\n";
        o << "    conditioned on the non-exercise of one or more of the rights that are\n";
        o << "    specifically granted under this License.  You may not convey a covered\n";
        o << "    work if you are a party to an arrangement with a third party that is\n";
        o << "    in the business of distributing software, under which you make payment\n";
        o << "    to the third party based on the extent of your activity of conveying\n";
        o << "    the work, and under which the third party grants, to any of the\n";
        o << "    parties who would receive the covered work from you, a discriminatory\n";
        o << "    patent license (a) in connection with copies of the covered work\n";
        o << "    conveyed by you (or copies made from those copies), or (b) primarily\n";
        o << "    for and in connection with specific products or compilations that\n";
        o << "    contain the covered work, unless you entered into that arrangement,\n";
        o << "    or that patent license was granted, prior to 28 March 2007.\n";
        o << "\n";
        o << "    Nothing in this License shall be construed as excluding or limiting\n";
        o << "    any implied license or other defenses to infringement that may\n";
        o << "    otherwise be available to you under applicable patent law.\n";
        o << "\n";
        o << "    12. No Surrender of Others' Freedom.\n";
        o << "\n";
        o << "    If conditions are imposed on you (whether by court order, agreement or\n";
        o << "    otherwise) that contradict the conditions of this License, they do not\n";
        o << "    excuse you from the conditions of this License.  If you cannot convey a\n";
        o << "    covered work so as to satisfy simultaneously your obligations under this\n";
        o << "    License and any other pertinent obligations, then as a consequence you may\n";
        o << "    not convey it at all.  For example, if you agree to terms that obligate you\n";
        o << "    to collect a royalty for further conveying from those to whom you convey\n";
        o << "    the Program, the only way you could satisfy both those terms and this\n";
        o << "    License would be to refrain entirely from conveying the Program.\n";
        o << "\n";
        o << "    13. Use with the GNU Affero General Public License.\n";
        o << "\n";
        o << "    Notwithstanding any other provision of this License, you have\n";
        o << "    permission to link or combine any covered work with a work licensed\n";
        o << "    under version 3 of the GNU Affero General Public License into a single\n";
        o << "    combined work, and to convey the resulting work.  The terms of this\n";
        o << "    License will continue to apply to the part which is the covered work,\n";
        o << "    but the special requirements of the GNU Affero General Public License,\n";
        o << "    section 13, concerning interaction through a network will apply to the\n";
        o << "    combination as such.\n";
        o << "\n";
        o << "    14. Revised Versions of this License.\n";
        o << "\n";
        o << "    The Free Software Foundation may publish revised and/or new versions of\n";
        o << "    the GNU General Public License from time to time.  Such new versions will\n";
        o << "    be similar in spirit to the present version, but may differ in detail to\n";
        o << "    address new problems or concerns.\n";
        o << "\n";
        o << "    Each version is given a distinguishing version number.  If the\n";
        o << "    Program specifies that a certain numbered version of the GNU General\n";
        o << "    Public License \"or any later version\" applies to it, you have the\n";
        o << "    option of following the terms and conditions either of that numbered\n";
        o << "    version or of any later version published by the Free Software\n";
        o << "    Foundation.  If the Program does not specify a version number of the\n";
        o << "    GNU General Public License, you may choose any version ever published\n";
        o << "    by the Free Software Foundation.\n";
        o << "\n";
        o << "    If the Program specifies that a proxy can decide which future\n";
        o << "    versions of the GNU General Public License can be used, that proxy's\n";
        o << "    public statement of acceptance of a version permanently authorizes you\n";
        o << "    to choose that version for the Program.\n";
        o << "\n";
        o << "    Later license versions may give you additional or different\n";
        o << "    permissions.  However, no additional obligations are imposed on any\n";
        o << "    author or copyright holder as a result of your choosing to follow a\n";
        o << "    later version.\n";
        o << "\n";
        o << "    15. Disclaimer of Warranty.\n";
        o << "\n";
        o << "    THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY\n";
        o << "    APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT\n";
        o << "    HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY\n";
        o << "    OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,\n";
        o << "    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n";
        o << "    PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM\n";
        o << "    IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF\n";
        o << "    ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n";
        o << "\n";
        o << "    16. Limitation of Liability.\n";
        o << "\n";
        o << "    IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n";
        o << "    WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS\n";
        o << "    THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY\n";
        o << "    GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE\n";
        o << "    USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF\n";
        o << "    DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD\n";
        o << "    PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),\n";
        o << "    EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF\n";
        o << "    SUCH DAMAGES.\n";
        o << "\n";
        o << "    17. Interpretation of Sections 15 and 16.\n";
        o << "\n";
        o << "    If the disclaimer of warranty and limitation of liability provided\n";
        o << "    above cannot be given local legal effect according to their terms,\n";
        o << "    reviewing courts shall apply local law that most closely approximates\n";
        o << "    an absolute waiver of all civil liability in connection with the\n";
        o << "    Program, unless a warranty or assumption of liability accompanies a\n";
        o << "    copy of the Program in return for a fee.\n";
        o << "\n";
        o << "    END OF TERMS AND CONDITIONS\n";
        o << "\n";
        o << "    How to Apply These Terms to Your New Programs\n";
        o << "\n";
        o << "    If you develop a new program, and you want it to be of the greatest\n";
        o << "    possible use to the public, the best way to achieve this is to make it\n";
        o << "    free software which everyone can redistribute and change under these terms.\n";
        o << "\n";
        o << "    To do so, attach the following notices to the program.  It is safest\n";
        o << "    to attach them to the start of each source file to most effectively\n";
        o << "    state the exclusion of warranty; and each file should have at least\n";
        o << "    the \"copyright\" line and a pointer to where the full notice is found.\n";
        o << "\n";
        o << "    <one line to give the program's name and a brief idea of what it does.>\n";
        o << "    Copyright (C) <year>  <name of author>\n";
        o << "\n";
        o << "    This program is free software: you can redistribute it and/or modify\n";
        o << "    it under the terms of the GNU General Public License as published by\n";
        o << "    the Free Software Foundation, either version 3 of the License, or\n";
        o << "    (at your option) any later version.\n";
        o << "\n";
        o << "    This program is distributed in the hope that it will be useful,\n";
        o << "    but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
        o << "    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n";
        o << "    GNU General Public License for more details.\n";
        o << "\n";
        o << "    You should have received a copy of the GNU General Public License\n";
        o << "    along with this program.  If not, see <http://www.gnu.org/licenses/>.\n";
        o << "\n";
        o << "    Also add information on how to contact you by electronic and paper mail.\n";
        o << "\n";
        o << "    If the program does terminal interaction, make it output a short\n";
        o << "    notice like this when it starts in an interactive mode:\n";
        o << "\n";
        o << "    {{ project }}  Copyright (C) {{ year }}  {{ organization }}\n";
        o << "    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.\n";
        o << "    This is free software, and you are welcome to redistribute it\n";
        o << "    under certain conditions; type `show c' for details.\n";
        o << "\n";
        o << "    The hypothetical commands `show w' and `show c' should show the appropriate\n";
        o << "    parts of the General Public License.  Of course, your program's commands\n";
        o << "    might be different; for a GUI interface, you would use an \"about box\".\n";
        o << "\n";
        o << "    You should also get your employer (if you work as a programmer) or school,\n";
        o << "    if any, to sign a \"copyright disclaimer\" for the program, if necessary.\n";
        o << "    For more information on this, and how to apply and follow the GNU GPL, see\n";
        o << "    <http://www.gnu.org/licenses/>.\n";
        o << "\n";
        o << "    The GNU General Public License does not permit incorporating your program\n";
        o << "    into proprietary programs.  If your program is a subroutine library, you\n";
        o << "    may consider it more useful to permit linking proprietary applications with\n";
        o << "    the library.  If this is what you want to do, use the GNU Lesser General\n";
        o << "    Public License instead of this License.  But first, please read\n";
        o << "    <http://www.gnu.org/philosophy/why-not-lgpl.html>.\n";
    }
    o << "\n";
    o << "\n";
    // #################################################################################################################
    // #################################################################################################################
    // cxxopts
    // #################################################################################################################
    // #################################################################################################################
    o << "cxxopts Library (https://github.com/jarro2783/cxxopts)\n";
    o << "\n";
    o << "    MIT License\n";
    if (full) {
        o << "\n";
        o << "    Copyright (c) 2014 Jarryd Beck\n";
        o << "\n";
        o << "    Permission is hereby granted, free of charge, to any person obtaining a copy\n";
        o << "    of this software and associated documentation files (the \"Software\"), to deal\n";
        o << "    in the Software without restriction, including without limitation the rights\n";
        o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n";
        o << "    copies of the Software, and to permit persons to whom the Software is\n";
        o << "    furnished to do so, subject to the following conditions:\n";
        o << "\n";
        o << "    The above copyright notice and this permission notice shall be included in\n";
        o << "    all copies or substantial portions of the Software.\n";
        o << "\n";
        o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n";
        o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n";
        o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n";
        o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n";
        o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n";
        o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n";
        o << "    THE SOFTWARE.\n";
    }
    o << "\n";
    o << "\n";
    // #################################################################################################################
    // #################################################################################################################
    // libmodbus
    // #################################################################################################################
    // #################################################################################################################
    o << "Modbus Library (https://github.com/stephane/libmodbus):\n";
    o << "\n";
    o << "    LGPLv2.1\n";
    if (full) {
        o << "\n";
        o << "                      GNU LESSER GENERAL PUBLIC LICENSE\n";
        o << "                           Version 2.1, February 1999\n";
        o << "\n";
        o << "     Copyright (C) 1991, 1999 Free Software Foundation, Inc.\n";
        o << "     51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA\n";
        o << "     Everyone is permitted to copy and distribute verbatim copies\n";
        o << "     of this license document, but changing it is not allowed.\n";
        o << "\n";
        o << "    [This is the first released version of the Lesser GPL.  It also counts\n";
        o << "     as the successor of the GNU Library Public License, version 2, hence\n";
        o << "     the version number 2.1.]\n";
        o << "\n";
        o << "                                Preamble\n";
        o << "\n";
        o << "      The licenses for most software are designed to take away your\n";
        o << "    freedom to share and change it.  By contrast, the GNU General Public\n";
        o << "    Licenses are intended to guarantee your freedom to share and change\n";
        o << "    free software--to make sure the software is free for all its users.\n";
        o << "\n";
        o << "      This license, the Lesser General Public License, applies to some\n";
        o << "    specially designated software packages--typically libraries--of the\n";
        o << "    Free Software Foundation and other authors who decide to use it.  You\n";
        o << "    can use it too, but we suggest you first think carefully about whether\n";
        o << "    this license or the ordinary General Public License is the better\n";
        o << "    strategy to use in any particular case, based on the explanations below.\n";
        o << "\n";
        o << "      When we speak of free software, we are referring to freedom of use,\n";
        o << "    not price.  Our General Public Licenses are designed to make sure that\n";
        o << "    you have the freedom to distribute copies of free software (and charge\n";
        o << "    for this service if you wish); that you receive source code or can get\n";
        o << "    it if you want it; that you can change the software and use pieces of\n";
        o << "    it in new free programs; and that you are informed that you can do\n";
        o << "    these things.\n";
        o << "\n";
        o << "      To protect your rights, we need to make restrictions that forbid\n";
        o << "    distributors to deny you these rights or to ask you to surrender these\n";
        o << "    rights.  These restrictions translate to certain responsibilities for\n";
        o << "    you if you distribute copies of the library or if you modify it.\n";
        o << "\n";
        o << "      For example, if you distribute copies of the library, whether gratis\n";
        o << "    or for a fee, you must give the recipients all the rights that we gave\n";
        o << "    you.  You must make sure that they, too, receive or can get the source\n";
        o << "    code.  If you link other code with the library, you must provide\n";
        o << "    complete object files to the recipients, so that they can relink them\n";
        o << "    with the library after making changes to the library and recompiling\n";
        o << "    it.  And you must show them these terms so they know their rights.\n";
        o << "\n";
        o << "      We protect your rights with a two-step method: (1) we copyright the\n";
        o << "    library, and (2) we offer you this license, which gives you legal\n";
        o << "    permission to copy, distribute and/or modify the library.\n";
        o << "\n";
        o << "      To protect each distributor, we want to make it very clear that\n";
        o << "    there is no warranty for the free library.  Also, if the library is\n";
        o << "    modified by someone else and passed on, the recipients should know\n";
        o << "    that what they have is not the original version, so that the original\n";
        o << "    author's reputation will not be affected by problems that might be\n";
        o << "    introduced by others.\n";
        o << "\n";
        o << "      Finally, software patents pose a constant threat to the existence of\n";
        o << "    any free program.  We wish to make sure that a company cannot\n";
        o << "    effectively restrict the users of a free program by obtaining a\n";
        o << "    restrictive license from a patent holder.  Therefore, we insist that\n";
        o << "    any patent license obtained for a version of the library must be\n";
        o << "    consistent with the full freedom of use specified in this license.\n";
        o << "\n";
        o << "      Most GNU software, including some libraries, is covered by the\n";
        o << "    ordinary GNU General Public License.  This license, the GNU Lesser\n";
        o << "    General Public License, applies to certain designated libraries, and\n";
        o << "    is quite different from the ordinary General Public License.  We use\n";
        o << "    this license for certain libraries in order to permit linking those\n";
        o << "    libraries into non-free programs.\n";
        o << "\n";
        o << "      When a program is linked with a library, whether statically or using\n";
        o << "    a shared library, the combination of the two is legally speaking a\n";
        o << "    combined work, a derivative of the original library.  The ordinary\n";
        o << "    General Public License therefore permits such linking only if the\n";
        o << "    entire combination fits its criteria of freedom.  The Lesser General\n";
        o << "    Public License permits more lax criteria for linking other code with\n";
        o << "    the library.\n";
        o << "\n";
        o << "      We call this license the \"Lesser\" General Public License because it\n";
        o << "    does Less to protect the user's freedom than the ordinary General\n";
        o << "    Public License.  It also provides other free software developers Less\n";
        o << "    of an advantage over competing non-free programs.  These disadvantages\n";
        o << "    are the reason we use the ordinary General Public License for many\n";
        o << "    libraries.  However, the Lesser license provides advantages in certain\n";
        o << "    special circumstances.\n";
        o << "\n";
        o << "      For example, on rare occasions, there may be a special need to\n";
        o << "    encourage the widest possible use of a certain library, so that it becomes\n";
        o << "    a de-facto standard.  To achieve this, non-free programs must be\n";
        o << "    allowed to use the library.  A more frequent case is that a free\n";
        o << "    library does the same job as widely used non-free libraries.  In this\n";
        o << "    case, there is little to gain by limiting the free library to free\n";
        o << "    software only, so we use the Lesser General Public License.\n";
        o << "\n";
        o << "      In other cases, permission to use a particular library in non-free\n";
        o << "    programs enables a greater number of people to use a large body of\n";
        o << "    free software.  For example, permission to use the GNU C Library in\n";
        o << "    non-free programs enables many more people to use the whole GNU\n";
        o << "    operating system, as well as its variant, the GNU/Linux operating\n";
        o << "    system.\n";
        o << "\n";
        o << "      Although the Lesser General Public License is Less protective of the\n";
        o << "    users' freedom, it does ensure that the user of a program that is\n";
        o << "    linked with the Library has the freedom and the wherewithal to run\n";
        o << "    that program using a modified version of the Library.\n";
        o << "\n";
        o << "      The precise terms and conditions for copying, distribution and\n";
        o << "    modification follow.  Pay close attention to the difference between a\n";
        o << "    \"work based on the library\" and a \"work that uses the library\".  The\n";
        o << "    former contains code derived from the library, whereas the latter must\n";
        o << "    be combined with the library in order to run.\n";
        o << "\n";
        o << "                      GNU LESSER GENERAL PUBLIC LICENSE\n";
        o << "       TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n";
        o << "\n";
        o << "      0. This License Agreement applies to any software library or other\n";
        o << "    program which contains a notice placed by the copyright holder or\n";
        o << "    other authorized party saying it may be distributed under the terms of\n";
        o << "    this Lesser General Public License (also called \"this License\").\n";
        o << "    Each licensee is addressed as \"you\".\n";
        o << "\n";
        o << "      A \"library\" means a collection of software functions and/or data\n";
        o << "    prepared so as to be conveniently linked with application programs\n";
        o << "    (which use some of those functions and data) to form executables.\n";
        o << "\n";
        o << "      The \"Library\", below, refers to any such software library or work\n";
        o << "    which has been distributed under these terms.  A \"work based on the\n";
        o << "    Library\" means either the Library or any derivative work under\n";
        o << "    copyright law: that is to say, a work containing the Library or a\n";
        o << "    portion of it, either verbatim or with modifications and/or translated\n";
        o << "    straightforwardly into another language.  (Hereinafter, translation is\n";
        o << "    included without limitation in the term \"modification\".)\n";
        o << "\n";
        o << "      \"Source code\" for a work means the preferred form of the work for\n";
        o << "    making modifications to it.  For a library, complete source code means\n";
        o << "    all the source code for all modules it contains, plus any associated\n";
        o << "    interface definition files, plus the scripts used to control compilation\n";
        o << "    and installation of the library.\n";
        o << "\n";
        o << "      Activities other than copying, distribution and modification are not\n";
        o << "    covered by this License; they are outside its scope.  The act of\n";
        o << "    running a program using the Library is not restricted, and output from\n";
        o << "    such a program is covered only if its contents constitute a work based\n";
        o << "    on the Library (independent of the use of the Library in a tool for\n";
        o << "    writing it).  Whether that is true depends on what the Library does\n";
        o << "    and what the program that uses the Library does.\n";
        o << "\n";
        o << "      1. You may copy and distribute verbatim copies of the Library's\n";
        o << "    complete source code as you receive it, in any medium, provided that\n";
        o << "    you conspicuously and appropriately publish on each copy an\n";
        o << "    appropriate copyright notice and disclaimer of warranty; keep intact\n";
        o << "    all the notices that refer to this License and to the absence of any\n";
        o << "    warranty; and distribute a copy of this License along with the\n";
        o << "    Library.\n";
        o << "\n";
        o << "      You may charge a fee for the physical act of transferring a copy,\n";
        o << "    and you may at your option offer warranty protection in exchange for a\n";
        o << "    fee.\n";
        o << "\n";
        o << "      2. You may modify your copy or copies of the Library or any portion\n";
        o << "    of it, thus forming a work based on the Library, and copy and\n";
        o << "    distribute such modifications or work under the terms of Section 1\n";
        o << "    above, provided that you also meet all of these conditions:\n";
        o << "\n";
        o << "        a) The modified work must itself be a software library.\n";
        o << "\n";
        o << "        b) You must cause the files modified to carry prominent notices\n";
        o << "        stating that you changed the files and the date of any change.\n";
        o << "\n";
        o << "        c) You must cause the whole of the work to be licensed at no\n";
        o << "        charge to all third parties under the terms of this License.\n";
        o << "\n";
        o << "        d) If a facility in the modified Library refers to a function or a\n";
        o << "        table of data to be supplied by an application program that uses\n";
        o << "        the facility, other than as an argument passed when the facility\n";
        o << "        is invoked, then you must make a good faith effort to ensure that,\n";
        o << "        in the event an application does not supply such function or\n";
        o << "        table, the facility still operates, and performs whatever part of\n";
        o << "        its purpose remains meaningful.\n";
        o << "\n";
        o << "        (For example, a function in a library to compute square roots has\n";
        o << "        a purpose that is entirely well-defined independent of the\n";
        o << "        application.  Therefore, Subsection 2d requires that any\n";
        o << "        application-supplied function or table used by this function must\n";
        o << "        be optional: if the application does not supply it, the square\n";
        o << "        root function must still compute square roots.)\n";
        o << "\n";
        o << "    These requirements apply to the modified work as a whole.  If\n";
        o << "    identifiable sections of that work are not derived from the Library,\n";
        o << "    and can be reasonably considered independent and separate works in\n";
        o << "    themselves, then this License, and its terms, do not apply to those\n";
        o << "    sections when you distribute them as separate works.  But when you\n";
        o << "    distribute the same sections as part of a whole which is a work based\n";
        o << "    on the Library, the distribution of the whole must be on the terms of\n";
        o << "    this License, whose permissions for other licensees extend to the\n";
        o << "    entire whole, and thus to each and every part regardless of who wrote\n";
        o << "    it.\n";
        o << "\n";
        o << "    Thus, it is not the intent of this section to claim rights or contest\n";
        o << "    your rights to work written entirely by you; rather, the intent is to\n";
        o << "    exercise the right to control the distribution of derivative or\n";
        o << "    collective works based on the Library.\n";
        o << "\n";
        o << "    In addition, mere aggregation of another work not based on the Library\n";
        o << "    with the Library (or with a work based on the Library) on a volume of\n";
        o << "    a storage or distribution medium does not bring the other work under\n";
        o << "    the scope of this License.\n";
        o << "\n";
        o << "      3. You may opt to apply the terms of the ordinary GNU General Public\n";
        o << "    License instead of this License to a given copy of the Library.  To do\n";
        o << "    this, you must alter all the notices that refer to this License, so\n";
        o << "    that they refer to the ordinary GNU General Public License, version 2,\n";
        o << "    instead of to this License.  (If a newer version than version 2 of the\n";
        o << "    ordinary GNU General Public License has appeared, then you can specify\n";
        o << "    that version instead if you wish.)  Do not make any other change in\n";
        o << "    these notices.\n";
        o << "\n";
        o << "      Once this change is made in a given copy, it is irreversible for\n";
        o << "    that copy, so the ordinary GNU General Public License applies to all\n";
        o << "    subsequent copies and derivative works made from that copy.\n";
        o << "\n";
        o << "      This option is useful when you wish to copy part of the code of\n";
        o << "    the Library into a program that is not a library.\n";
        o << "\n";
        o << "      4. You may copy and distribute the Library (or a portion or\n";
        o << "    derivative of it, under Section 2) in object code or executable form\n";
        o << "    under the terms of Sections 1 and 2 above provided that you accompany\n";
        o << "    it with the complete corresponding machine-readable source code, which\n";
        o << "    must be distributed under the terms of Sections 1 and 2 above on a\n";
        o << "    medium customarily used for software interchange.\n";
        o << "\n";
        o << "      If distribution of object code is made by offering access to copy\n";
        o << "    from a designated place, then offering equivalent access to copy the\n";
        o << "    source code from the same place satisfies the requirement to\n";
        o << "    distribute the source code, even though third parties are not\n";
        o << "    compelled to copy the source along with the object code.\n";
        o << "\n";
        o << "      5. A program that contains no derivative of any portion of the\n";
        o << "    Library, but is designed to work with the Library by being compiled or\n";
        o << "    linked with it, is called a \"work that uses the Library\".  Such a\n";
        o << "    work, in isolation, is not a derivative work of the Library, and\n";
        o << "    therefore falls outside the scope of this License.\n";
        o << "\n";
        o << "      However, linking a \"work that uses the Library\" with the Library\n";
        o << "    creates an executable that is a derivative of the Library (because it\n";
        o << "    contains portions of the Library), rather than a \"work that uses the\n";
        o << "    library\".  The executable is therefore covered by this License.\n";
        o << "    Section 6 states terms for distribution of such executables.\n";
        o << "\n";
        o << "      When a \"work that uses the Library\" uses material from a header file\n";
        o << "    that is part of the Library, the object code for the work may be a\n";
        o << "    derivative work of the Library even though the source code is not.\n";
        o << "    Whether this is true is especially significant if the work can be\n";
        o << "    linked without the Library, or if the work is itself a library.  The\n";
        o << "    threshold for this to be true is not precisely defined by law.\n";
        o << "\n";
        o << "      If such an object file uses only numerical parameters, data\n";
        o << "    structure layouts and accessors, and small macros and small inline\n";
        o << "    functions (ten lines or less in length), then the use of the object\n";
        o << "    file is unrestricted, regardless of whether it is legally a derivative\n";
        o << "    work.  (Executables containing this object code plus portions of the\n";
        o << "    Library will still fall under Section 6.)\n";
        o << "\n";
        o << "      Otherwise, if the work is a derivative of the Library, you may\n";
        o << "    distribute the object code for the work under the terms of Section 6.\n";
        o << "    Any executables containing that work also fall under Section 6,\n";
        o << "    whether or not they are linked directly with the Library itself.\n";
        o << "\n";
        o << "      6. As an exception to the Sections above, you may also combine or\n";
        o << "    link a \"work that uses the Library\" with the Library to produce a\n";
        o << "    work containing portions of the Library, and distribute that work\n";
        o << "    under terms of your choice, provided that the terms permit\n";
        o << "    modification of the work for the customer's own use and reverse\n";
        o << "    engineering for debugging such modifications.\n";
        o << "\n";
        o << "      You must give prominent notice with each copy of the work that the\n";
        o << "    Library is used in it and that the Library and its use are covered by\n";
        o << "    this License.  You must supply a copy of this License.  If the work\n";
        o << "    during execution displays copyright notices, you must include the\n";
        o << "    copyright notice for the Library among them, as well as a reference\n";
        o << "    directing the user to the copy of this License.  Also, you must do one\n";
        o << "    of these things:\n";
        o << "\n";
        o << "        a) Accompany the work with the complete corresponding\n";
        o << "        machine-readable source code for the Library including whatever\n";
        o << "        changes were used in the work (which must be distributed under\n";
        o << "        Sections 1 and 2 above); and, if the work is an executable linked\n";
        o << "        with the Library, with the complete machine-readable \"work that\n";
        o << "        uses the Library\", as object code and/or source code, so that the\n";
        o << "        user can modify the Library and then relink to produce a modified\n";
        o << "        executable containing the modified Library.  (It is understood\n";
        o << "        that the user who changes the contents of definitions files in the\n";
        o << "        Library will not necessarily be able to recompile the application\n";
        o << "        to use the modified definitions.)\n";
        o << "\n";
        o << "        b) Use a suitable shared library mechanism for linking with the\n";
        o << "        Library.  A suitable mechanism is one that (1) uses at run time a\n";
        o << "        copy of the library already present on the user's computer system,\n";
        o << "        rather than copying library functions into the executable, and (2)\n";
        o << "        will operate properly with a modified version of the library, if\n";
        o << "        the user installs one, as long as the modified version is\n";
        o << "        interface-compatible with the version that the work was made with.\n";
        o << "\n";
        o << "        c) Accompany the work with a written offer, valid for at\n";
        o << "        least three years, to give the same user the materials\n";
        o << "        specified in Subsection 6a, above, for a charge no more\n";
        o << "        than the cost of performing this distribution.\n";
        o << "\n";
        o << "        d) If distribution of the work is made by offering access to copy\n";
        o << "        from a designated place, offer equivalent access to copy the above\n";
        o << "        specified materials from the same place.\n";
        o << "\n";
        o << "        e) Verify that the user has already received a copy of these\n";
        o << "        materials or that you have already sent this user a copy.\n";
        o << "\n";
        o << "      For an executable, the required form of the \"work that uses the\n";
        o << "    Library\" must include any data and utility programs needed for\n";
        o << "    reproducing the executable from it.  However, as a special exception,\n";
        o << "    the materials to be distributed need not include anything that is\n";
        o << "    normally distributed (in either source or binary form) with the major\n";
        o << "    components (compiler, kernel, and so on) of the operating system on\n";
        o << "    which the executable runs, unless that component itself accompanies\n";
        o << "    the executable.\n";
        o << "\n";
        o << "      It may happen that this requirement contradicts the license\n";
        o << "    restrictions of other proprietary libraries that do not normally\n";
        o << "    accompany the operating system.  Such a contradiction means you cannot\n";
        o << "    use both them and the Library together in an executable that you\n";
        o << "    distribute.\n";
        o << "\n";
        o << "      7. You may place library facilities that are a work based on the\n";
        o << "    Library side-by-side in a single library together with other library\n";
        o << "    facilities not covered by this License, and distribute such a combined\n";
        o << "    library, provided that the separate distribution of the work based on\n";
        o << "    the Library and of the other library facilities is otherwise\n";
        o << "    permitted, and provided that you do these two things:\n";
        o << "\n";
        o << "        a) Accompany the combined library with a copy of the same work\n";
        o << "        based on the Library, uncombined with any other library\n";
        o << "        facilities.  This must be distributed under the terms of the\n";
        o << "        Sections above.\n";
        o << "\n";
        o << "        b) Give prominent notice with the combined library of the fact\n";
        o << "        that part of it is a work based on the Library, and explaining\n";
        o << "        where to find the accompanying uncombined form of the same work.\n";
        o << "\n";
        o << "      8. You may not copy, modify, sublicense, link with, or distribute\n";
        o << "    the Library except as expressly provided under this License.  Any\n";
        o << "    attempt otherwise to copy, modify, sublicense, link with, or\n";
        o << "    distribute the Library is void, and will automatically terminate your\n";
        o << "    rights under this License.  However, parties who have received copies,\n";
        o << "    or rights, from you under this License will not have their licenses\n";
        o << "    terminated so long as such parties remain in full compliance.\n";
        o << "\n";
        o << "      9. You are not required to accept this License, since you have not\n";
        o << "    signed it.  However, nothing else grants you permission to modify or\n";
        o << "    distribute the Library or its derivative works.  These actions are\n";
        o << "    prohibited by law if you do not accept this License.  Therefore, by\n";
        o << "    modifying or distributing the Library (or any work based on the\n";
        o << "    Library), you indicate your acceptance of this License to do so, and\n";
        o << "    all its terms and conditions for copying, distributing or modifying\n";
        o << "    the Library or works based on it.\n";
        o << "\n";
        o << "      10. Each time you redistribute the Library (or any work based on the\n";
        o << "    Library), the recipient automatically receives a license from the\n";
        o << "    original licensor to copy, distribute, link with or modify the Library\n";
        o << "    subject to these terms and conditions.  You may not impose any further\n";
        o << "    restrictions on the recipients' exercise of the rights granted herein.\n";
        o << "    You are not responsible for enforcing compliance by third parties with\n";
        o << "    this License.\n";
        o << "\n";
        o << "      11. If, as a consequence of a court judgment or allegation of patent\n";
        o << "    infringement or for any other reason (not limited to patent issues),\n";
        o << "    conditions are imposed on you (whether by court order, agreement or\n";
        o << "    otherwise) that contradict the conditions of this License, they do not\n";
        o << "    excuse you from the conditions of this License.  If you cannot\n";
        o << "    distribute so as to satisfy simultaneously your obligations under this\n";
        o << "    License and any other pertinent obligations, then as a consequence you\n";
        o << "    may not distribute the Library at all.  For example, if a patent\n";
        o << "    license would not permit royalty-free redistribution of the Library by\n";
        o << "    all those who receive copies directly or indirectly through you, then\n";
        o << "    the only way you could satisfy both it and this License would be to\n";
        o << "    refrain entirely from distribution of the Library.\n";
        o << "\n";
        o << "    If any portion of this section is held invalid or unenforceable under any\n";
        o << "    particular circumstance, the balance of the section is intended to apply,\n";
        o << "    and the section as a whole is intended to apply in other circumstances.\n";
        o << "\n";
        o << "    It is not the purpose of this section to induce you to infringe any\n";
        o << "    patents or other property right claims or to contest validity of any\n";
        o << "    such claims; this section has the sole purpose of protecting the\n";
        o << "    integrity of the free software distribution system which is\n";
        o << "    implemented by public license practices.  Many people have made\n";
        o << "    generous contributions to the wide range of software distributed\n";
        o << "    through that system in reliance on consistent application of that\n";
        o << "    system; it is up to the author/donor to decide if he or she is willing\n";
        o << "    to distribute software through any other system and a licensee cannot\n";
        o << "    impose that choice.\n";
        o << "\n";
        o << "    This section is intended to make thoroughly clear what is believed to\n";
        o << "    be a consequence of the rest of this License.\n";
        o << "\n";
        o << "      12. If the distribution and/or use of the Library is restricted in\n";
        o << "    certain countries either by patents or by copyrighted interfaces, the\n";
        o << "    original copyright holder who places the Library under this License may add\n";
        o << "    an explicit geographical distribution limitation excluding those countries,\n";
        o << "    so that distribution is permitted only in or among countries not thus\n";
        o << "    excluded.  In such case, this License incorporates the limitation as if\n";
        o << "    written in the body of this License.\n";
        o << "\n";
        o << "      13. The Free Software Foundation may publish revised and/or new\n";
        o << "    versions of the Lesser General Public License from time to time.\n";
        o << "    Such new versions will be similar in spirit to the present version,\n";
        o << "    but may differ in detail to address new problems or concerns.\n";
        o << "\n";
        o << "    Each version is given a distinguishing version number.  If the Library\n";
        o << "    specifies a version number of this License which applies to it and\n";
        o << "    \"any later version\", you have the option of following the terms and\n";
        o << "    conditions either of that version or of any later version published by\n";
        o << "    the Free Software Foundation.  If the Library does not specify a\n";
        o << "    license version number, you may choose any version ever published by\n";
        o << "    the Free Software Foundation.\n";
        o << "\n";
        o << "      14. If you wish to incorporate parts of the Library into other free\n";
        o << "    programs whose distribution conditions are incompatible with these,\n";
        o << "    write to the author to ask for permission.  For software which is\n";
        o << "    copyrighted by the Free Software Foundation, write to the Free\n";
        o << "    Software Foundation; we sometimes make exceptions for this.  Our\n";
        o << "    decision will be guided by the two goals of preserving the free status\n";
        o << "    of all derivatives of our free software and of promoting the sharing\n";
        o << "    and reuse of software generally.\n";
        o << "\n";
        o << "                                NO WARRANTY\n";
        o << "\n";
        o << "      15. BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE IS NO\n";
        o << "    WARRANTY FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE LAW.\n";
        o << "    EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR\n";
        o << "    OTHER PARTIES PROVIDE THE LIBRARY \"AS IS\" WITHOUT WARRANTY OF ANY\n";
        o << "    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE\n";
        o << "    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n";
        o << "    PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE\n";
        o << "    LIBRARY IS WITH YOU.  SHOULD THE LIBRARY PROVE DEFECTIVE, YOU ASSUME\n";
        o << "    THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n";
        o << "\n";
        o << "      16. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN\n";
        o << "    WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY\n";
        o << "    AND/OR REDISTRIBUTE THE LIBRARY AS PERMITTED ABOVE, BE LIABLE TO YOU\n";
        o << "    FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR\n";
        o << "    CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE\n";
        o << "    LIBRARY (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING\n";
        o << "    RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A\n";
        o << "    FAILURE OF THE LIBRARY TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF\n";
        o << "    SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n";
        o << "    DAMAGES.\n";
        o << "\n";
        o << "                         END OF TERMS AND CONDITIONS\n";
        o << "\n";
        o << "               How to Apply These Terms to Your New Libraries\n";
        o << "\n";
        o << "      If you develop a new library, and you want it to be of the greatest\n";
        o << "    possible use to the public, we recommend making it free software that\n";
        o << "    everyone can redistribute and change.  You can do so by permitting\n";
        o << "    redistribution under these terms (or, alternatively, under the terms of the\n";
        o << "    ordinary General Public License).\n";
        o << "\n";
        o << "      To apply these terms, attach the following notices to the library.  It is\n";
        o << "    safest to attach them to the start of each source file to most effectively\n";
        o << "    convey the exclusion of warranty; and each file should have at least the\n";
        o << "    \"copyright\" line and a pointer to where the full notice is found.\n";
        o << "\n";
        o << "        <one line to give the library's name and a brief idea of what it does.>\n";
        o << "        Copyright (C) <year>  <name of author>\n";
        o << "\n";
        o << "        This library is free software; you can redistribute it and/or\n";
        o << "        modify it under the terms of the GNU Lesser General Public\n";
        o << "        License as published by the Free Software Foundation; either\n";
        o << "        version 2.1 of the License, or (at your option) any later version.\n";
        o << "\n";
        o << "        This library is distributed in the hope that it will be useful,\n";
        o << "        but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
        o << "        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n";
        o << "        Lesser General Public License for more details.\n";
        o << "\n";
        o << "        You should have received a copy of the GNU Lesser General Public\n";
        o << "        License along with this library; if not, write to the Free Software\n";
        o << "        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA\n";
        o << "\n";
        o << "    Also add information on how to contact you by electronic and paper mail.\n";
        o << "\n";
        o << "    You should also get your employer (if you work as a programmer) or your\n";
        o << "    school, if any, to sign a \"copyright disclaimer\" for the library, if\n";
        o << "    necessary.  Here is a sample; alter the names:\n";
        o << "\n";
        o << "      Yoyodyne, Inc., hereby disclaims all copyright interest in the\n";
        o << "      library `Frob' (a library for tweaking knobs) written by James Random Hacker.\n";
        o << "\n";
        o << "      <signature of Ty Coon>, 1 April 1990\n";
        o << "      Ty Coon, President of Vice\n";
        o << "\n";
        o << "    That's all there is to it!\n";
    }
    o << "\n";
    o << "\n";
    // #################################################################################################################
    // #################################################################################################################
    // cxxshm
    // #################################################################################################################
    // #################################################################################################################
    o << "cxxshm Library (https://github.com/NikolasK-source/cxxshm)\n";
    o << "\n";
    o << "    MIT License\n";
    if (full) {
        o << "\n";
        o << "    Copyright (c) 2022 Nikolas Koesling\n";
        o << "\n";
        o << "    Permission is hereby granted, free of charge, to any person obtaining a copy\n";
        o << "    of this software and associated documentation files (the \"Software\"), to deal\n";
        o << "    in the Software without restriction, including without limitation the rights\n";
        o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n";
        o << "    copies of the Software, and to permit persons to whom the Software is\n";
        o << "    furnished to do so, subject to the following conditions:\n";
        o << "\n";
        o << "    The above copyright notice and this permission notice shall be included in all\n";
        o << "    copies or substantial portions of the Software.\n";
        o << "\n";
        o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n";
        o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n";
        o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n";
        o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n";
        o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n";
        o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n";
        o << "    SOFTWARE.\n";
    }
    o << "\n";
    o << "\n";
    // #################################################################################################################
    // #################################################################################################################
    // cxxsemaphore
    // #################################################################################################################
    // #################################################################################################################
    o << "cxxsemaphore Library (https://github.com/NikolasK-source/cxxsemaphore)\n";
    o << "\n";
    o << "    MIT License\n";
    if (full) {
        o << "\n";
        o << "    Copyright (c) 2023 Nikolas Koesling\n";
        o << "\n";
        o << "    Permission is hereby granted, free of charge, to any person obtaining a copy\n";
        o << "    of this software and associated documentation files (the \"Software\"), to deal\n";
        o << "    in the Software without restriction, including without limitation the rights\n";
        o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n";
        o << "    copies of the Software, and to permit persons to whom the Software is\n";
        o << "    furnished to do so, subject to the following conditions:\n";
        o << "\n";
        o << "    The above copyright notice and this permission notice shall be included in all\n";
        o << "    copies or substantial portions of the Software.\n";
        o << "\n";
        o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n";
        o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n";
        o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n";
        o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n";
        o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n";
        o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n";
        o << "    SOFTWARE.\n";
    }
    o.flush();
}
